"""profile picture and cover

Revision ID: d53213ad0acc
Revises: b5b96ed07f24
Create Date: 2021-11-23 17:07:02.458939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53213ad0acc'
down_revision = 'b5b96ed07f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cover_photo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_photo')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
